id: AFC875D54
base_file: f7704.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 18:53:14.181832
  last_modified_at: 2022-05-30 18:53:14.181841
